admittance_controller:
  ros__parameters:
    enable_parameter_update_without_reactivation: true
    type: ur5e_admittance_control/AdmittanceController
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

    ft_sensor:
      name: tcp_fts_sensor
      filter_coefficient: 0.005

    admittance:
      selected_axes:
        - true # x
        - true # y
        - false # z
        - true # rx
        - true # ry
        - true # rz

    mass:
      - 20.0
      - 20.0
      - 20.0
      - 0.2
      - 0.2
      - 0.2

    # damping_ratio: # damping can be used instead: zeta = D / (2 * sqrt( M * S ))
    #   - 2.828427 # x
    #   - 2.828427 # y
    #   - 2.828427 # z
    #   - 2.828427 # rx
    #   - 2.828427 # ry
    #   - 2.828427 # rz

    damping:
      - 40.0
      - 40.0
      - 40.0
      - 4.0
      - 4.0
      - 4.0


    stiffness:
      - 450.0
      - 450.0
      - 450.0
      - 25.0
      - 25.0
      - 25.0

    wrench_deadband: 5.5
    max_position_offset: 0.01
    max_position_step: 0.002