admittance_controller:
  ros__parameters:
    type: ur5e_admittance_control/AdmittanceController
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

    ft_sensor:
      name: tcp_fts_sensor
      filter_coefficient: 0.005

    mass:
      - 2.0
      - 2.0
      - 2.0
      - 0.2
      - 0.2
      - 0.2

    damping:
      - 40.0
      - 40.0
      - 40.0
      - 4.0
      - 4.0
      - 4.0

    stiffness:
      - 250.0
      - 250.0
      - 250.0
      - 25.0
      - 25.0
      - 25.0

    wrench_deadband: 0.5
    max_position_offset: 0.05